============= Configurations =============
dataset:brats
model:ae
in_channels:1
input_size:64
base_width:16
expansion:1
mid_num:1024
latent_size:16
en_num_layers:1
de_num_layers:1
epochs:250
batch_size:64
lr:0.001
weight_decay:0
seed:328111
num_params:2.3512M
FLOPs:29.8967M
=> Initial learning rate: 0.001
Traceback (most recent call last):
  File "/home/ahmad/Desktop/Graduation Proj/MedIAnomaly/reconstruction/train.py", line 43, in <module>
    main()
  File "/home/ahmad/Desktop/Graduation Proj/MedIAnomaly/reconstruction/train.py", line 39, in main
    worker.run_train()
  File "/home/ahmad/Desktop/Graduation Proj/MedIAnomaly/reconstruction/utils/ae_worker.py", line 225, in run_train
    eval_results = self.evaluate()
  File "/home/ahmad/Desktop/Graduation Proj/MedIAnomaly/reconstruction/utils/ae_worker.py", line 100, in evaluate
    anomaly_score_map = self.criterion(img, net_out, anomaly_score=True, keepdim=True).detach().cpu()
  File "/home/ahmad/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ahmad/anaconda3/envs/torch/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ahmad/Desktop/Graduation Proj/MedIAnomaly/reconstruction/utils/losses.py", line 59, in forward
    return torch.mean(total_loss, dim=[1], keepdim=True) if keepdim else torch.mean(total_loss, dim=[1, 2, 3])
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)